### PR TITLE
Moving to the head of the base rocket project

### PR DESCRIPTION
**Pull request by alkama**
- reintegrate changes from kusma's master branch.
- have the OGL editor use the current "sync" library structure.
- add an optional cmake-based build system (only for OSX for now).

### CODE REVIEW

**Comment by alkama** [comment]
Had to make some very unclean changes, like:
- copying enums (for GET_TRACK and SET_ROW) because in the base project they got buried into the device.c file.
- polluting the RemoteConnection.c file to add missing socket things that were originally in the sync base.h but now are hidden into c files.
- rewrite dedicated sync_find_track and sync_create_track because data.c and .h disappeared and sync_data structure got removed and integrated directly into the device in the original project.

So it will probably need further cleaning.
Sorry for that !
Also, I havent checked for windows and linux behavior.

**Comment by emoon** [comment]
Thanks! I think it would be nice to squash all the kusmas commits into one to keep the history a bit cleaner if possible.

**Comment by alkama** [comment]
You're right!
Done.
I force-pushed the squashing on my repo, hope this wont have side impacts :)
(Also squashing lost the merge link info.)

**Comment by emoon** [comment]
Thanks!

**Pull request merged**
